import { 
  FaSearch, 
  FaFileAlt, 
  FaComments, 
  FaVideo, 
  FaDollarSign, 
  FaCalendarAlt, 
  FaExclamationTriangle, 
  FaMapMarkerAlt, 
  FaHome, 
  FaStore, 
  FaCar, 
  FaPlane, 
  FaBriefcase, 
  FaPuzzlePiece 
} from 'react-icons/fa';
import type { NodeType } from './types';

export const evidenceNodeTypes: NodeType[] = [
  {
    id: 'evidence',
    label: 'Evidence',
    icon: FaSearch,
    color: 'bg-orange-600',
    description: 'Physical evidence, photos, or forensic data',
    category: 'evidence',
    properties: [
      { id: 'type', label: 'Evidence Type', type: 'select', options: ['Physical', 'Digital', 'Documentary', 'Testimonial', 'Circumstantial', 'DNA', 'Fingerprint', 'Photo', 'Video', 'Audio', 'Other'], required: true },
      { id: 'title', label: 'Evidence Title', type: 'text', required: true, placeholder: 'Fingerprint from Crime Scene' },
      { id: 'description', label: 'Description', type: 'textarea', placeholder: 'Latent fingerprint found on window frame' },
      { id: 'location', label: 'Location Found', type: 'text', placeholder: '123 Main Street, Apartment 2B' },
      { id: 'dateFound', label: 'Date Found', type: 'date', placeholder: '2024-01-15' },
      { id: 'foundBy', label: 'Found By', type: 'text', placeholder: 'Detective Smith' },
      { id: 'chainOfCustody', label: 'Chain of Custody', type: 'textarea', placeholder: 'Smith → Johnson → Lab' },
      { id: 'status', label: 'Status', type: 'select', options: ['Collected', 'In Analysis', 'Analyzed', 'Stored', 'Destroyed', 'Returned'] },
      { id: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { id: 'filePath', label: 'File Path', type: 'text', placeholder: '/evidence/fingerprints/fp-001.jpg' },
      { id: 'hash', label: 'File Hash', type: 'text', placeholder: 'a1b2c3d4e5f6...' },
      { id: 'analysis', label: 'Analysis Results', type: 'textarea', placeholder: 'Matches suspect John Doe' },
      { id: 'analyst', label: 'Analyst', type: 'text', placeholder: 'Dr. Jane Wilson' },
      { id: 'lab', label: 'Laboratory', type: 'text', placeholder: 'State Crime Lab' },
      { id: 'caseNumber', label: 'Case Number', type: 'text', placeholder: 'CASE-2024-001' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'document',
    label: 'Document',
    icon: FaFileAlt,
    color: 'bg-yellow-600',
    description: 'Files, reports, emails, or written evidence',
    category: 'evidence',
    properties: [
      { id: 'title', label: 'Document Title', type: 'text', required: true, placeholder: 'Q4 Financial Report' },
      { id: 'type', label: 'Document Type', type: 'select', options: ['Email', 'Report', 'Contract', 'Invoice', 'Receipt', 'Certificate', 'License', 'Passport', 'ID Card', 'Photo', 'Video', 'Audio', 'Other'] },
      { id: 'author', label: 'Author', type: 'text', placeholder: 'John Smith' },
      { id: 'recipient', label: 'Recipient', type: 'text', placeholder: 'Jane Doe' },
      { id: 'createdDate', label: 'Created Date', type: 'date', placeholder: '2024-01-15' },
      { id: 'modifiedDate', label: 'Modified Date', type: 'date', placeholder: '2024-01-16' },
      { id: 'fileSize', label: 'File Size', type: 'text', placeholder: '2.5 MB' },
      { id: 'fileFormat', label: 'File Format', type: 'text', placeholder: 'PDF' },
      { id: 'filePath', label: 'File Path', type: 'text', placeholder: '/documents/reports/q4-2024.pdf' },
      { id: 'url', label: 'URL', type: 'url', placeholder: 'https://example.com/document.pdf' },
      { id: 'hash', label: 'File Hash', type: 'text', placeholder: 'a1b2c3d4e5f6...' },
      { id: 'language', label: 'Language', type: 'text', placeholder: 'English' },
      { id: 'pages', label: 'Number of Pages', type: 'number', placeholder: '25' },
      { id: 'confidentiality', label: 'Confidentiality Level', type: 'select', options: ['Public', 'Internal', 'Confidential', 'Secret', 'Top Secret'] },
      { id: 'classification', label: 'Classification', type: 'select', options: ['Unclassified', 'Confidential', 'Secret', 'Top Secret'] },
      { id: 'retention', label: 'Retention Period', type: 'text', placeholder: '7 years' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'communication',
    label: 'Communication',
    icon: FaComments,
    color: 'bg-indigo-600',
    description: 'Phone calls, messages, or conversations',
    category: 'evidence',
    properties: [
      { id: 'type', label: 'Communication Type', type: 'select', options: ['Phone Call', 'Email', 'SMS', 'WhatsApp', 'Telegram', 'Signal', 'Zoom', 'Teams', 'Skype', 'In-Person', 'Other'], required: true },
      { id: 'from', label: 'From', type: 'text', required: true, placeholder: 'John Smith' },
      { id: 'to', label: 'To', type: 'text', required: true, placeholder: 'Jane Doe' },
      { id: 'date', label: 'Date/Time', type: 'date', required: true, placeholder: '2024-01-15' },
      { id: 'duration', label: 'Duration', type: 'text', placeholder: '15 minutes' },
      { id: 'subject', label: 'Subject', type: 'text', placeholder: 'Project Discussion' },
      { id: 'content', label: 'Content/Message', type: 'textarea', placeholder: 'Meeting scheduled for tomorrow at 2 PM' },
      { id: 'direction', label: 'Direction', type: 'select', options: ['Incoming', 'Outgoing', 'Both'] },
      { id: 'status', label: 'Status', type: 'select', options: ['Delivered', 'Read', 'Failed', 'Pending', 'Unknown'] },
      { id: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Urgent'] },
      { id: 'confidentiality', label: 'Confidentiality Level', type: 'select', options: ['Public', 'Internal', 'Confidential', 'Secret', 'Top Secret'] },
      { id: 'device', label: 'Device Used', type: 'text', placeholder: 'iPhone 15' },
      { id: 'network', label: 'Network/Carrier', type: 'text', placeholder: 'Verizon' },
      { id: 'location', label: 'Location', type: 'text', placeholder: 'New York, NY' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'media',
    label: 'Media File',
    icon: FaVideo,
    color: 'bg-pink-600',
    description: 'Photos, videos, audio recordings, or other media files',
    category: 'evidence',
    properties: [
      { id: 'filename', label: 'Filename', type: 'text', required: true, placeholder: 'video_001.mp4' },
      { id: 'type', label: 'Media Type', type: 'select', options: ['Photo', 'Video', 'Audio', 'Document', 'Other'] },
      { id: 'format', label: 'File Format', type: 'text', placeholder: 'MP4, JPEG, MP3, etc.' },
      { id: 'fileSize', label: 'File Size', type: 'text', placeholder: '25.5 MB' },
      { id: 'duration', label: 'Duration', type: 'text', placeholder: '5:30' },
      { id: 'resolution', label: 'Resolution', type: 'text', placeholder: '1920x1080' },
      { id: 'createdDate', label: 'Created Date', type: 'date', placeholder: '2024-01-15' },
      { id: 'location', label: 'Location', type: 'text', placeholder: 'Where the media was captured' },
      { id: 'device', label: 'Device Used', type: 'text', placeholder: 'iPhone 15 Pro' },
      { id: 'owner', label: 'Owner', type: 'text', placeholder: 'John Smith' },
      { id: 'hash', label: 'File Hash', type: 'text', placeholder: 'a1b2c3d4e5f6...' },
      { id: 'metadata', label: 'Metadata', type: 'textarea', placeholder: 'EXIF data, GPS coordinates, etc.' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'financial',
    label: 'Financial Account',
    icon: FaDollarSign,
    color: 'bg-emerald-600',
    description: 'Bank accounts, credit cards, or financial instruments',
    category: 'evidence',
    properties: [
      { id: 'type', label: 'Account Type', type: 'select', options: ['Bank Account', 'Credit Card', 'Investment', 'Loan', 'Insurance', 'Tax Return', 'Payroll', 'Invoice', 'Receipt', 'Other'], required: true },
      { id: 'accountNumber', label: 'Account Number', type: 'text', placeholder: '1234567890' },
      { id: 'routingNumber', label: 'Routing Number', type: 'text', placeholder: '021000021' },
      { id: 'bankName', label: 'Bank Name', type: 'text', placeholder: 'Chase Bank' },
      { id: 'accountHolder', label: 'Account Holder', type: 'text', placeholder: 'John Smith' },
      { id: 'balance', label: 'Balance', type: 'text', placeholder: '$5,000.00' },
      { id: 'currency', label: 'Currency', type: 'select', options: ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'Other'] },
      { id: 'transactionDate', label: 'Transaction Date', type: 'date', placeholder: '2024-01-15' },
      { id: 'amount', label: 'Amount', type: 'text', placeholder: '$250.00' },
      { id: 'description', label: 'Description', type: 'text', placeholder: 'Grocery Store Purchase' },
      { id: 'merchant', label: 'Merchant', type: 'text', placeholder: 'Whole Foods' },
      { id: 'category', label: 'Category', type: 'select', options: ['Food', 'Transportation', 'Entertainment', 'Healthcare', 'Education', 'Housing', 'Utilities', 'Other'] },
      { id: 'status', label: 'Status', type: 'select', options: ['Active', 'Closed', 'Suspended', 'Pending', 'Failed'] },
      { id: 'interestRate', label: 'Interest Rate', type: 'text', placeholder: '3.5%' },
      { id: 'creditLimit', label: 'Credit Limit', type: 'text', placeholder: '$10,000' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'event',
    label: 'Event',
    icon: FaCalendarAlt,
    color: 'bg-purple-600',
    description: 'Meetings, incidents, or time-based occurrences',
    category: 'evidence',
    properties: [
      { id: 'title', label: 'Event Title', type: 'text', required: true, placeholder: 'Board Meeting' },
      { id: 'type', label: 'Event Type', type: 'select', options: ['Meeting', 'Conference', 'Incident', 'Celebration', 'Training', 'Interview', 'Court Hearing', 'Medical Appointment', 'Other'] },
      { id: 'startDate', label: 'Start Date/Time', type: 'date', required: true, placeholder: '2024-01-15' },
      { id: 'endDate', label: 'End Date/Time', type: 'date', placeholder: '2024-01-15' },
      { id: 'location', label: 'Location', type: 'text', placeholder: 'Conference Room A' },
      { id: 'organizer', label: 'Organizer', type: 'text', placeholder: 'John Smith' },
      { id: 'attendees', label: 'Attendees', type: 'textarea', placeholder: 'Jane Doe, Bob Johnson, Alice Brown' },
      { id: 'agenda', label: 'Agenda', type: 'textarea', placeholder: '1. Review Q4 results\n2. Discuss budget\n3. Plan Q1 initiatives' },
      { id: 'outcome', label: 'Outcome/Result', type: 'textarea', placeholder: 'Budget approved, new initiatives planned' },
      { id: 'status', label: 'Status', type: 'select', options: ['Scheduled', 'In Progress', 'Completed', 'Cancelled', 'Postponed'] },
      { id: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { id: 'confidentiality', label: 'Confidentiality Level', type: 'select', options: ['Public', 'Internal', 'Confidential', 'Secret', 'Top Secret'] },
      { id: 'cost', label: 'Cost', type: 'text', placeholder: '$500' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'incident',
    label: 'Incident',
    icon: FaExclamationTriangle,
    color: 'bg-red-600',
    description: 'Crimes, accidents, or other incidents requiring investigation',
    category: 'evidence',
    properties: [
      { id: 'title', label: 'Incident Title', type: 'text', required: true, placeholder: 'Bank Robbery' },
      { id: 'type', label: 'Incident Type', type: 'select', options: ['Crime', 'Accident', 'Security Breach', 'Fraud', 'Theft', 'Assault', 'Cyber Attack', 'Other'] },
      { id: 'date', label: 'Incident Date', type: 'date', required: true, placeholder: '2024-01-15' },
      { id: 'time', label: 'Time', type: 'text', placeholder: '2:30 PM' },
      { id: 'location', label: 'Location', type: 'text', placeholder: '123 Main Street' },
      { id: 'description', label: 'Description', type: 'textarea', placeholder: 'Detailed description of what happened...' },
      { id: 'victims', label: 'Victims', type: 'textarea', placeholder: 'Names of victims involved...' },
      { id: 'suspects', label: 'Suspects', type: 'textarea', placeholder: 'Names of suspects...' },
      { id: 'witnesses', label: 'Witnesses', type: 'textarea', placeholder: 'Names of witnesses...' },
      { id: 'evidence', label: 'Evidence', type: 'textarea', placeholder: 'Physical evidence collected...' },
      { id: 'officer', label: 'Investigating Officer', type: 'text', placeholder: 'Detective Smith' },
      { id: 'caseNumber', label: 'Case Number', type: 'text', placeholder: 'CASE-2024-001' },
      { id: 'status', label: 'Status', type: 'select', options: ['Open', 'Under Investigation', 'Closed', 'Solved', 'Unsolved'] },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'location',
    label: 'Location',
    icon: FaMapMarkerAlt,
    color: 'bg-red-600',
    description: 'Places, addresses, or geographical locations',
    category: 'evidence',
    properties: [
      { id: 'name', label: 'Location Name', type: 'text', required: true, placeholder: 'Central Park' },
      { id: 'type', label: 'Location Type', type: 'select', options: ['Residence', 'Business', 'Public Space', 'Government Building', 'Educational Institution', 'Religious Site', 'Transportation Hub', 'Recreational Area', 'Other'] },
      { id: 'address', label: 'Street Address', type: 'text', placeholder: '123 Main Street' },
      { id: 'city', label: 'City', type: 'text', placeholder: 'New York' },
      { id: 'state', label: 'State/Province', type: 'text', placeholder: 'NY' },
      { id: 'zipCode', label: 'ZIP/Postal Code', type: 'text', placeholder: '10001' },
      { id: 'country', label: 'Country', type: 'text', placeholder: 'United States' },
      { id: 'latitude', label: 'Latitude', type: 'number', placeholder: '40.7128' },
      { id: 'longitude', label: 'Longitude', type: 'number', placeholder: '-74.0060' },
      { id: 'building', label: 'Building Name', type: 'text', placeholder: 'Empire State Building' },
      { id: 'floor', label: 'Floor', type: 'text', placeholder: '15th Floor' },
      { id: 'room', label: 'Room/Unit', type: 'text', placeholder: 'Room 1501' },
      { id: 'access', label: 'Access Level', type: 'select', options: ['Public', 'Private', 'Restricted', 'Secure', 'Unknown'] },
      { id: 'hours', label: 'Operating Hours', type: 'text', placeholder: '9 AM - 5 PM' },
      { id: 'owner', label: 'Owner', type: 'text', placeholder: 'John Smith' },
      { id: 'manager', label: 'Manager', type: 'text', placeholder: 'Jane Doe' },
      { id: 'capacity', label: 'Capacity', type: 'number', placeholder: '100' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'residence',
    label: 'Residence',
    icon: FaHome,
    color: 'bg-orange-600',
    description: 'Homes, apartments, or residential properties',
    category: 'evidence',
    properties: [
      { id: 'address', label: 'Address', type: 'text', required: true, placeholder: '123 Main Street' },
      { id: 'type', label: 'Residence Type', type: 'select', options: ['House', 'Apartment', 'Condo', 'Townhouse', 'Mobile Home', 'Duplex', 'Other'] },
      { id: 'city', label: 'City', type: 'text', placeholder: 'New York' },
      { id: 'state', label: 'State', type: 'text', placeholder: 'NY' },
      { id: 'zipCode', label: 'ZIP Code', type: 'text', placeholder: '10001' },
      { id: 'owner', label: 'Owner', type: 'text', placeholder: 'John Smith' },
      { id: 'resident', label: 'Primary Resident', type: 'text', placeholder: 'Jane Doe' },
      { id: 'bedrooms', label: 'Bedrooms', type: 'number', placeholder: '3' },
      { id: 'bathrooms', label: 'Bathrooms', type: 'number', placeholder: '2' },
      { id: 'squareFeet', label: 'Square Feet', type: 'number', placeholder: '1500' },
      { id: 'yearBuilt', label: 'Year Built', type: 'number', placeholder: '1995' },
      { id: 'value', label: 'Property Value', type: 'text', placeholder: '$500,000' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'business',
    label: 'Business Location',
    icon: FaStore,
    color: 'bg-yellow-600',
    description: 'Commercial establishments, stores, offices, or business premises',
    category: 'evidence',
    properties: [
      { id: 'name', label: 'Business Name', type: 'text', required: true, placeholder: 'Acme Store' },
      { id: 'type', label: 'Business Type', type: 'select', options: ['Retail Store', 'Restaurant', 'Office', 'Warehouse', 'Factory', 'Service', 'Entertainment', 'Other'] },
      { id: 'address', label: 'Address', type: 'text', placeholder: '123 Business Ave' },
      { id: 'city', label: 'City', type: 'text', placeholder: 'New York' },
      { id: 'state', label: 'State', type: 'text', placeholder: 'NY' },
      { id: 'zipCode', label: 'ZIP Code', type: 'text', placeholder: '10001' },
      { id: 'owner', label: 'Owner', type: 'text', placeholder: 'John Smith' },
      { id: 'manager', label: 'Manager', type: 'text', placeholder: 'Jane Doe' },
      { id: 'phone', label: 'Phone', type: 'phone', placeholder: '+1-555-123-4567' },
      { id: 'website', label: 'Website', type: 'url', placeholder: 'https://www.acmestore.com' },
      { id: 'hours', label: 'Operating Hours', type: 'text', placeholder: '9 AM - 9 PM' },
      { id: 'employees', label: 'Number of Employees', type: 'number', placeholder: '25' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'vehicle',
    label: 'Vehicle',
    icon: FaCar,
    color: 'bg-gray-600',
    description: 'Cars, trucks, motorcycles, or other vehicles',
    category: 'evidence',
    properties: [
      { id: 'make', label: 'Make', type: 'text', required: true, placeholder: 'Toyota' },
      { id: 'model', label: 'Model', type: 'text', required: true, placeholder: 'Camry' },
      { id: 'year', label: 'Year', type: 'number', placeholder: '2020' },
      { id: 'vin', label: 'VIN', type: 'text', placeholder: '1HGBH41JXMN109186' },
      { id: 'licensePlate', label: 'License Plate', type: 'text', placeholder: 'ABC123' },
      { id: 'state', label: 'Registration State', type: 'text', placeholder: 'CA' },
      { id: 'owner', label: 'Owner', type: 'text', placeholder: 'John Smith' },
      { id: 'color', label: 'Color', type: 'text', placeholder: 'Silver' },
      { id: 'type', label: 'Vehicle Type', type: 'select', options: ['Sedan', 'SUV', 'Truck', 'Motorcycle', 'Bus', 'Van', 'Other'] },
      { id: 'status', label: 'Status', type: 'select', options: ['Active', 'Stolen', 'Recovered', 'Destroyed', 'Unknown'] },
      { id: 'lastSeen', label: 'Last Seen', type: 'date', placeholder: '2024-01-15' },
      { id: 'lastLocation', label: 'Last Known Location', type: 'text', placeholder: '123 Main Street' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'aircraft',
    label: 'Aircraft',
    icon: FaPlane,
    color: 'bg-blue-600',
    description: 'Planes, helicopters, or other aircraft',
    category: 'evidence',
    properties: [
      { id: 'type', label: 'Aircraft Type', type: 'select', options: ['Commercial Airline', 'Private Jet', 'Helicopter', 'Military', 'Cargo', 'Other'], required: true },
      { id: 'make', label: 'Make', type: 'text', placeholder: 'Boeing' },
      { id: 'model', label: 'Model', type: 'text', placeholder: '737' },
      { id: 'registration', label: 'Registration', type: 'text', placeholder: 'N12345' },
      { id: 'tailNumber', label: 'Tail Number', type: 'text', placeholder: 'N12345' },
      { id: 'owner', label: 'Owner', type: 'text', placeholder: 'American Airlines' },
      { id: 'operator', label: 'Operator', type: 'text', placeholder: 'Pilot Name' },
      { id: 'departure', label: 'Departure', type: 'text', placeholder: 'JFK Airport' },
      { id: 'arrival', label: 'Arrival', type: 'text', placeholder: 'LAX Airport' },
      { id: 'flightDate', label: 'Flight Date', type: 'date', placeholder: '2024-01-15' },
      { id: 'passengers', label: 'Number of Passengers', type: 'number', placeholder: '150' },
      { id: 'status', label: 'Status', type: 'select', options: ['Active', 'Maintenance', 'Retired', 'Unknown'] },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'case',
    label: 'Case',
    icon: FaBriefcase,
    color: 'bg-gray-600',
    description: 'Investigation cases, legal cases, or project files',
    category: 'evidence',
    properties: [
      { id: 'caseNumber', label: 'Case Number', type: 'text', required: true, placeholder: 'CASE-2024-001' },
      { id: 'title', label: 'Case Title', type: 'text', required: true, placeholder: 'Bank Robbery Investigation' },
      { id: 'type', label: 'Case Type', type: 'select', options: ['Criminal', 'Civil', 'Administrative', 'Internal', 'Other'], required: true },
      { id: 'status', label: 'Status', type: 'select', options: ['Open', 'Under Investigation', 'Closed', 'Solved', 'Unsolved'], required: true },
      { id: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { id: 'assignedTo', label: 'Assigned To', type: 'text', placeholder: 'Detective Smith' },
      { id: 'supervisor', label: 'Supervisor', type: 'text', placeholder: 'Captain Johnson' },
      { id: 'openedDate', label: 'Opened Date', type: 'date', placeholder: '2024-01-15' },
      { id: 'closedDate', label: 'Closed Date', type: 'date', placeholder: '2024-02-15' },
      { id: 'description', label: 'Description', type: 'textarea', placeholder: 'Case description and details...' },
      { id: 'victims', label: 'Victims', type: 'textarea', placeholder: 'Names of victims...' },
      { id: 'suspects', label: 'Suspects', type: 'textarea', placeholder: 'Names of suspects...' },
      { id: 'evidence', label: 'Evidence', type: 'textarea', placeholder: 'Evidence collected...' },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  },
  {
    id: 'miscellaneous',
    label: 'Miscellaneous',
    icon: FaPuzzlePiece,
    color: 'bg-gray-500',
    description: 'Other items that don\'t fit into specific categories',
    category: 'evidence',
    properties: [
      { id: 'name', label: 'Item Name', type: 'text', required: true, placeholder: 'Item Name' },
      { id: 'type', label: 'Item Type', type: 'text', placeholder: 'Type of item' },
      { id: 'description', label: 'Description', type: 'textarea', placeholder: 'Detailed description...' },
      { id: 'location', label: 'Location', type: 'text', placeholder: 'Where item is located' },
      { id: 'owner', label: 'Owner', type: 'text', placeholder: 'Who owns this item' },
      { id: 'value', label: 'Value', type: 'text', placeholder: 'Monetary or other value' },
      { id: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Lost', 'Stolen', 'Destroyed', 'Unknown'] },
      { id: 'notes', label: 'Additional Notes', type: 'textarea', placeholder: 'Any additional information...' }
    ]
  }
];
